name: Build
on: [push]
jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: |
          sudo apt install -y qemu-user-static binfmt-support
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name builder
          docker buildx use builder
          docker buildx build --platform linux/arm/v7,linux/arm64 -t ghcr.io/falste/smarthome:latest --push .
