name: Build
on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-22.04-arm64   # <<< this is key
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/falste/smarthome:latest \
            --push .
